force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <label>Total_Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Total_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount__c</fullName>
    <label>Total_Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Count__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Count__c</fullName>
    <label>Transaction_Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TransactionItem__c/TransactionItem__c.object-meta.xml
<CustomObject>
    <label>TransactionItem</label>
    <nameField>
        <label>TransactionItem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TransactionItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionItem__c/fields/Item_Cost__c.field-meta.xml
<CustomField>
    <fullName>Item_Cost__c</fullName>
    <label>Item_Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TransactionItem__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>TransactionItem</relationshipLabel>
    <relationshipName>TransactionItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TransactItemsDetCalloutQueuableTest.cls
/*
Class Name: TransactItemsDetCalloutQueuableTest
Created By: Abhishek Vishwakarma 
Description: Callout Test Class 
*/

@isTest
private class TransactItemsDetCalloutQueuableTest {
    
    public static Set<Id> transactionIds = new set<Id>();
    public static List<TransactionItem__c> lstTransactionItemData;
    private static void createTransAndItemData(){
        
        lstTransactionItemData = new List<TransactionItem__c>();
        Transaction__c insertTransactionData = new Transaction__c(Total_Cost__c = 100,Total_Discount__c =10,Transaction_Count__c =3);        
        transactionIds.add(insertTransactionData.Id);
        insert insertTransactionData;
        
        lstTransactionItemData.add(new TransactionItem__c(Name = 'Test Tranascation Item 1',Item_Cost__c = 300,Transaction__c =insertTransactionData.id ));
        insert lstTransactionItemData; 
        
    }
    
    @isTest 
    static void testCallout() {
        
        //Setting my Mock up Class 
        Test.setMock(HttpCalloutMock.class, new TransImplementMock()); 
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        HttpResponse res = TransactionItemsDetailCalloutQueuable.makeCallout(lstTransactionItemData,'AuthCredentialsPOST');
        
        // Verify response received contains fake values
        String contentType = res.getHeader('Content-Type');
        System.assert(contentType == 'application/json');
        String actualValue = res.getBody();
        String expectedValue = '{"trail":"test"}';
        System.assertEquals(actualValue, expectedValue);
        System.assertEquals(200, res.getStatusCode());
    }
    
    static testMethod void makeCalloutTest(){
        
        createTransAndItemData();
        
        Test.startTest();
        TransactionItemsDetailCalloutQueuable.getAllAuthData('AuthCredentialsPOST');
        TransactionItemsDetailCalloutQueuable updater = new TransactionItemsDetailCalloutQueuable(transactionIds);
        system.enqueueJob(updater);
        Test.setMock(HttpCalloutMock.class, new TransImplementMock());   
        Test.stopTest();
    }
}